# Generated by Django 4.1.2 on 2022-11-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='displayName',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='authors',
            name='profileImage',
            field=models.TextField(),
        ),
    ]
