# Generated by Django 4.1.2 on 2022-11-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='password',
        ),
    ]
