# Generated by Django 4.1.2 on 2022-10-22 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(default='author', max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('displayName', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=255)),
                ('github', models.CharField(max_length=255)),
                ('accepted', models.BooleanField(default=True)),
                ('profileImage', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=16)),
                ('comment', models.CharField(max_length=255)),
                ('contentType', models.CharField(blank=True, choices=[('PT', 'PLAINTEXT'), ('CM', 'MARKDOWN')], default='PT', max_length=2, null=True)),
                ('published', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.authors')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='database.authors')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='database.authors')),
            ],
        ),
        migrations.CreateModel(
            name='FollowRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='database.authors')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='database.authors')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.authors')),
            ],
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.authors')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('context', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=16)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.authors')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(default='author', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('contentType', models.CharField(blank=True, choices=[('text/plain', 'PLAINTEXT'), ('text/markdown', 'COMMONMARK')], default='text/plain', max_length=15, null=True)),
                ('content', models.TextField()),
                ('count', models.IntegerField(default=0)),
                ('comments', models.CharField(max_length=255)),
                ('published', models.DateTimeField()),
                ('visibility', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('FRIENDS', 'FRIENDS')], default='PUBLIC', max_length=8)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.authors')),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='liked',
            name='like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.likes'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.posts'),
        ),
    ]
