# Generated by Django 4.1.2 on 2022-11-11 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_authors_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='imageContents',
            new_name='imageContent',
        ),
    ]
