# Generated by Django 4.1.2 on 2022-10-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_authors_comments_followers_followrequests_inbox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='unlisted',
        ),
        migrations.AlterField(
            model_name='authors',
            name='github',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('FRIENDS', 'FRIENDS'), ('UNLISTED', 'UNLISTED')], default='PUBLIC', max_length=8),
        ),
    ]
