# Generated by Django 4.1.2 on 2022-10-27 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_posts_unlisted_alter_authors_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='originalAuthor',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='originalPoster', to='database.authors'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='database.authors'),
        ),
        migrations.DeleteModel(
            name='Liked',
        ),
    ]
