# Generated by Django 4.1.2 on 2022-10-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_authors_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='displayName',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
