# Generated by Django 4.1.2 on 2022-11-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_rename_imagecontents_images_imagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'PLAINTEXT'), ('text/markdown', 'COMMONMARK'), ('image', 'IMAGE')], default='text/plain', max_length=15),
        ),
    ]
