# Generated by Django 4.1.2 on 2022-10-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_authors_displayname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
