# Generated by Django 4.1.2 on 2022-10-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_authors_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
