# Generated by Django 4.1.2 on 2022-10-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='title',
            new_name='authorId',
        ),
    ]
